### ISSUE TITLE
DeploymentBuild in abalone-cicd-pipeline, chapter 5. Running command  "npx cdk synth -o output" taking too long.

### ISSUE THREAD

**Issue by creative-h** [PacktPublishing/Automated-Machine-Learning-on-AWS#1]
[Container] 2022/07/28 02:24:27 Phase complete: INSTALL State: SUCCEEDED
95 | [Container] 2022/07/28 02:24:27 Phase context status code:  Message:
96 | [Container] 2022/07/28 02:24:27 Entering phase PRE_BUILD
97 | [Container] 2022/07/28 02:24:27 Phase complete: PRE_BUILD State: SUCCEEDED
98 | [Container] 2022/07/28 02:24:27 Phase context status code:  Message:
99 | [Container] 2022/07/28 02:24:27 Entering phase BUILD
100 | [Container] 2022/07/28 02:24:27 Running command echo Synthesizing cdk template
101 | Synthesizing cdk template
102 |  
103 | [Container] 2022/07/28 02:24:27 Running command npx cdk synth -o output
104

**Comment by darkreapyre** [comment]
Thank you for catching this. It seems that AWS has upgraded the CDK engine requirements for "node >= 14.15.0", while the CodeBuild environment uses "node = 12.22.12". To resolve this issue, the Chapter 5 code has been updated to use Node 14. 

To apply this fix, either destroy and re-deploy the CDK environment using the updated Chapter 5 code, or use the AWS  CodeBuild management console, and edit the `BuildSpec` for the `DeploymentBuild` project. Replace ```"nodejs": 12``` (on LINE 7), with ```"nodejs": 14```, as follows:

```json
{
  "version": "0.2",
  "phases": {
    "install": {
      "runtime-versions": {
        "python": 3.8,
        "nodejs": 14
      },
      "commands": [
        "echo Updatimg build environment",
        "npm install aws-cdk@2.3.0",
        "python -m pip install --upgrade pip",
        "python -m pip install -r requirements.txt"
      ]
    },
    "build": {
      "commands": [
        "echo Synthesizing cdk template",
        "npx cdk synth -o output"
      ]
    },
    "post_build": {
      "commands": [
        "python ./artifacts/scripts/deploy.py"
      ]
    }
  },
  "artifacts": {
    "base-directory": "output",
    "files": [
      "EndpointStack.template.json",
      "params.json"
    ]
  }
}
```
